version: '3.8'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: menu_user
      POSTGRES_PASSWORD: menu_pass
      POSTGRES_DB: menu_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  api:
    build: ./menu_api
    restart: always
    command: >
      sh -c "flake8 .
             python manage.py makemigrations --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
